### ISSUE TITLE
# Scrolling not working

### ISSUE THREAD

**Issue by Oskar1504** [fireship-io/flamethrower#30]
a element
```html
<li><a href="http://localhost:5501/#contact">Contact</a></li>
```
Creates url `http://localhost:5501/#contact/` => thinks its link => wont scroll

local debugging 
flamethrower.js:32 creates const o with value  `o = http://localhost:5501/#contact/`
which causes next `if` to `false `which would otherwise process the scroll
flamethrower.js:33 `if (e.preventDefault(), o != null && o.startsWith("#")) => false`

local dirty workaround
starting line flamethrower.js:31
```diff
if (t != null && t.hasAttribute("href")) {
  const o = t.getAttribute("href"), s = new URL(o, location.href);
- if (e.preventDefault(), o != null && o.startsWith("#"))
+ if (e.preventDefault(), o != null && o.includes("#"))
-   return w(o), { type: "scrolled" };
+   return w("#" + o.split("#")[1]), { type: "scrolled" };
  {
....
```
this will always scroll to the first # in the url. 

No time myself creating an PR maybe someone else can fix it.

**Comment by ekwoka** [comment]
> No time myself creating an PR maybe someone else can fix it.

Not sure how this makes sense. You can change the code and make the PR right in github. just press the `.` key on the repo

**Comment by Oskar1504** [comment]
With the newest build it just works fine. Idk what i did wrong.

> Not sure how this makes sense. You can change the code and make the PR right in github. just press the . key on the repo

I wanted to say that I personally didn't have time to adjust and do a PR.

**Comment by Oskar1504** [comment]
Works

**Comment by ekwoka** [comment]
In this case it looks like https://github.com/fireship-io/flamethrower/pull/25 inadvertently solved your issue in this case.

If you were using a path alone instead of including the host it would continue to not work as before.
