### ISSUE TITLE
Unable to get out of the site using browser's navigation button

### ISSUE THREAD

**Issue by dhirajgagrai** [fireship-io/flamethrower#55]
After serving it on http://localhost:3000, I manually typed the URL and it loaded the example site.

I can get out of this site if I press the back button now. But if I click on About and then try to do the same it fails to get me out.

The back button is highlighted but is not working.

**Comment by prowebat** [comment]
I have fixed this issue.
Problem was, that on the history popstate event, a new history item was pushed.
so you never could actually go back in the history.
