### ISSUE TITLE
[help] cannot find imported module

### ISSUE THREAD

**Issue by depapp** [fireship-io/flamethrower#59]
hello everyone,
I've tried to implement `page object model` for the `playwright test`, but I have an issue related to import module.

- here's my code
![image](https://user-images.githubusercontent.com/6134774/185839628-08e56d66-4472-4e1f-87f3-777ca016ebf1.png)

- folder structure
![image](https://user-images.githubusercontent.com/6134774/185839685-18d25c90-7661-4f7f-9b23-a56c313ae8bf.png)

- error message `Error: Cannot find module '/Users/user/open-source/flamethrower/test/home.page' imported from /Users/user/open-source/flamethrower/test/main.spec.ts`
![image](https://user-images.githubusercontent.com/6134774/185839770-fe4cd6bb-9ab5-467e-a2fb-2e1125c42969.png)

is there any missing configuration?
thanks in advance for any help 🙏🏻

**Comment by sidwebworks** [comment]
@depapp You can't import a typescript file directly like a regular JS module, you'll have to add some sort of build step or directly execute the tests using `vitest` in that case it will automatically build your typescript code before running it.

**Comment by depapp** [comment]
thanks for the help @sidwebworks 🙇🏻 
there are some `import` on the `/lib` dir https://github.com/fireship-io/flamethrower/blob/main/lib/main.ts#L1 and it's works.

but the `import` didn't works on `/test` dir. do I need to update the `tsconfig.json` file to solve this import issue @sidwebworks ? 🙏🏻

**Comment by sidwebworks** [comment]
Those imports only work after building the typescript files.

To fix the problem you're facing, first build the project then import the module from the build/output directory into your test.

**Comment by depapp** [comment]
noted @sidwebworks , thank you 🙇🏻

**Comment by sidwebworks** [comment]
Playwright is essentially just running chromium browser, just like you won't run typescript directly in the browser or Node its the same thing here.
