### ISSUE TITLE
Discussion: what are the differences between it and Navigo?

### ISSUE THREAD

**Issue by andre4ik3** [fireship-io/flamethrower#66]
I've seen the video, I know it's a bit of a meme, but there's a legitimate non-meme project similar to this called [Navigo](https://github.com/krasimir/navigo) that I've actually, non-ironically been using. This appears to be in early meme status, but Navigo's an actual thing you might wanna look at.

How I use it in my site: it's a simple HTML+CSS static docs site, it doesn't need javascript bloat. However, for people that have JS enabled, I provide a client side router that downloads all the doc pages HTML in the background on first load and from there on out it can work offline and on shitty internet connections. And it feels blazingly fast 🔥 🔥 🔥

**Comment by micziz** [comment]
Pros of flamethrower:

1) This was built yes as a meme, but with a specific use in mind. 

2) Only native browser api's

Cons:

1) A meme, not really known if this will grow.

2) NOT production ready

Pros of Navigo:

1) Stable: It's been around for a while

2) Active community: It will resolve bugs and help you when needed.

I don't think Navigo will influence much this project. Flamethrower is, a I said, built for a specific use in mind. Fireship built it with the intention of using it with other technologies to satisfy his needs for fireship.io. But you know, things cloud change.
