### ISSUE TITLE
Deno support?

### ISSUE THREAD

**Issue by andre4ik3** [fireship-io/flamethrower#68]
There is a fork https://github.com/MrKleeblatt/flamethrowerDeno that has Deno support. Maybe we can merge it to get Deno support in master for everyone?

(CC @MrKleeblatt)

**Comment by micziz** [comment]
Cool fork, and while it's slim, there is a chance that this gets merged! (I hope). Since it basically uses only web api's, it should work.

**Comment by MrKleeblatt** [comment]
I would love to see that :)

**Comment by boehs** [comment]
why does this need to support deno?

**Comment by MrKleeblatt** [comment]
@boehs Actually I have no idea. It's just because I hate tsc and want to use `deno bundle` instead. And it just looks so pretty when there aren't 1000 config files for tsc and whatever

**Comment by mikhi32** [comment]
Hey @MrKleeblatt! I suggest you make a separate folder for deno, update to the latest commit, and open a pr to see if this gets merged.

I don't think so tought, this project is mostly dead.

**Comment by andre4ik3** [comment]
Closing because issue is stale.
