### ISSUE TITLE
Flamethrower breaks mermaid.js

### ISSUE THREAD

**Issue by AlexMikhalev** [fireship-io/flamethrower#71]
Hello @fireship-io,
I like to use a this great project, but I could not get mermaid diagrams working with it. 
I tried to embed flamethrower into Zola blog, and managed to get TOC working, but I could not get mermaid diagrams rendered - I had to hit the refresh button in a browser for mermaid diagram to appear, despite flamethrower documentation saying scripts inside body reload, so I had to revert the change, despite adding flamethrower gave really good user experience overall. 
Commit history: https://github.com/reference-architecture-ai/reference-architecture.ai/commit/9f79341244c4b69c0b6731621afc32578d632507

Ways to replicate: 
Add example below into home and similar into about, switch between tabs. Observe markdown is not rendered. 
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>
<body>
  <div class="mermaid">
  graph LR
      A --- B
      B-->C[fa:fa-ban forbidden]
      B-->D(fa:fa-spinner);
  </div>
 <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
 <script>mermaid.initialize({startOnLoad:true});
</script>
</body>
</html>```

**Comment by prowebat** [comment]
I guess because the body onload event (or whichever mermaid uses) is not fired when navigating between the pages.

you would need tell mermaid, that a navigation happened, use this code instead of the mermaid.initialize:
```
// this should work on first load and also on navigation:
mermaid.init();
```

**Comment by AlexMikhalev** [comment]
That worked, thank you very much. With your help, I turned my Zola website into super fast.
